// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKknDXriZ0ho86L8Y7bXQ4BvnjrrBmqow',
    appId: '1:237401968119:web:72080894320f15d30872f2',
    messagingSenderId: '237401968119',
    projectId: 'recycleapp-2fa50',
    authDomain: 'recycleapp-2fa50.firebaseapp.com',
    storageBucket: 'recycleapp-2fa50.firebasestorage.app',
    measurementId: 'G-GEQW1FMRNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94co1XjVfoZfnCxITcNvrPBWg1SYWouE',
    appId: '1:237401968119:android:c6cd1d7ac4f44cc70872f2',
    messagingSenderId: '237401968119',
    projectId: 'recycleapp-2fa50',
    storageBucket: 'recycleapp-2fa50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCG59zztKoWz6GYOJT9i9bUXJkf2rX-8',
    appId: '1:237401968119:ios:64805464df2f00080872f2',
    messagingSenderId: '237401968119',
    projectId: 'recycleapp-2fa50',
    storageBucket: 'recycleapp-2fa50.firebasestorage.app',
    androidClientId: '237401968119-gb87tio04cqc2i25q8rq3c5htttaa8fg.apps.googleusercontent.com',
    iosClientId: '237401968119-50vhi563voosgoqt9ngb94105td43ktd.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvCG59zztKoWz6GYOJT9i9bUXJkf2rX-8',
    appId: '1:237401968119:ios:64805464df2f00080872f2',
    messagingSenderId: '237401968119',
    projectId: 'recycleapp-2fa50',
    storageBucket: 'recycleapp-2fa50.firebasestorage.app',
    androidClientId: '237401968119-gb87tio04cqc2i25q8rq3c5htttaa8fg.apps.googleusercontent.com',
    iosClientId: '237401968119-50vhi563voosgoqt9ngb94105td43ktd.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKknDXriZ0ho86L8Y7bXQ4BvnjrrBmqow',
    appId: '1:237401968119:web:78d5fd713bd89cdc0872f2',
    messagingSenderId: '237401968119',
    projectId: 'recycleapp-2fa50',
    authDomain: 'recycleapp-2fa50.firebaseapp.com',
    storageBucket: 'recycleapp-2fa50.firebasestorage.app',
    measurementId: 'G-B42VR3NGZE',
  );
}
